version: '3.4'

services:
  customerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

