version: '3.4'

networks:
  backend:

services:
  customerdb:
    container_name: customer_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=password@12345#
    networks:
       - backend
    ports:
       - 8001:1433 

  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    container_name: customerapi-backend
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    networks:
        - backend
    ports:
        - 8002:80
    environment:
      - DB_HOST=customerdb
      - DB_NAME=dms_customer
      - DB_SA_PASSWORD=password@12345#

  productdb:
    container_name: product-db
    image: mysql:8.1.0-oracle
    environment:
        - MYSQL_ROOT_PASSWORD=password@12345#
    networks:
        - backend
    ports:
        - 8003:3306

  productwebapi:
    image: ${DOCKER_REGISTRY-}productwebapi
    container_name: productapi-backend
    build:
      context: .
      dockerfile: ProductWebApi/Dockerfile
    networks:
        - backend
    ports:
        - 8004:80
    environment:
      - DB_HOST=productdb
      - DB_NAME=dms_product
      - DB_ROOT_PASSWORD=password@12345#
